# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  

    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        # test against supported Java version:
        java: [ '11', '12', '13', '14', '15', '16' ]
        

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
